name: NN-CI

on:
  push:

defaults:
  run:
    working-directory: components/stun

jobs:
  build-and-test:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v2
      - name: Install boost test
        run: sudo apt-get update && sudo apt-get install -y libboost-test-dev
      - name: Configure cmake
        run: mkdir build && cd build && cmake -DSTUN_BUILD_TESTS=ON ../ci-build
      - name: Build
        run: cmake --build build --parallel
      - name: Test
        run: ./build/stun_test
